spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hubs
    driver-class-name: org.postgresql.Driver
    username: hub_service
    password: hub
    hikari:
      maximum-pool-size: 4
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: hub-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

server:
  port: 19095


