spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hubs
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  application:
    name: hub-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19095


